title: Jan von Bassewitz
logo: assets/img/profile.jpg
email: vbjan[at]ethz[dot]ch
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
remote_theme: BDHU/minimalist
favicon: false
description: Data Science MSc, Mechanical Eng BSc
google_site_verification: kUSxny4hzPIV1wHVbL6y4xt7SgXTgT4PxRGna47eboE

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vbjan/
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vbjan
  - name: Teaching
    icon: <i class="fa-solid fa-pen"></i>
    link: https://vbjan.github.io/teaching.html
  - name: Google Scholar
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://scholar.google.de/citations?user=GTk71FcAAAAJ


# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
