title: Jan von Bassewitz
logo: assets/img/jan_small.jpg
email: jan-philipp[at]<br>bassewitz[dot]biz
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
remote_theme: BDHU/minimalist
favicon: true
description: Data Science MSc, Mechanical Eng BSc
google_site_verification: kUSxny4hzPIV1wHVbL6y4xt7SgXTgT4PxRGna47eboE

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vbjan/
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vbjan
  - name: Teaching
    icon: <i class="fa-solid fa-pen"></i>
    link: https://vbjan.github.io/teaching.html
  - name: Google Scholar
    icon: <i class='fas fa-graduation-cap'></i> # Assuming you're using FontAwesome for icons
    link: https://scholar.google.de/citations?user=GTk71FcAAAAJ


# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
