title: Jan-Philipp von Bassewitz
logo: assets/img/jan_small.jpg
email: jan-philipp[at]bassewitz[dot]biz
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
remote_theme: BDHU/minimalist
favicon: true
description: Data Science MSc, Mechanical Eng BSc
google_site_verification: kUSxny4hzPIV1wHVbL6y4xt7SgXTgT4PxRGna47eboE

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: CV
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="2"><path stroke-linecap="round" d="M4 4v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8.342a2 2 0 0 0-.602-1.43l-4.44-4.342A2 2 0 0 0 13.56 2H6a2 2 0 0 0-2 2Zm5 9h6m-6 4h3"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/></g></svg>
    link: ./assets/docs/CV_Jan.pdf
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vbjan/
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vbjan
  - name: Teaching
    icon: <i class="fa-solid fa-pen"></i>
    link: ./teaching.html



# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
